// Code generated by protoc-gen-go.
// source: server/register.proto
// DO NOT EDIT!

/*
Package server is a generated protocol buffer package.

It is generated from these files:
	server/register.proto

It has these top-level messages:
	Register
*/
package server

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Register struct {
	Jobs []*Register_Job `protobuf:"bytes,1,rep,name=jobs" json:"jobs,omitempty"`
}

func (m *Register) Reset()         { *m = Register{} }
func (m *Register) String() string { return proto.CompactTextString(m) }
func (*Register) ProtoMessage()    {}

func (m *Register) GetJobs() []*Register_Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

type Register_Job struct {
	ServerLocation string `protobuf:"bytes,1,opt,name=serverLocation" json:"serverLocation,omitempty"`
	JobName        string `protobuf:"bytes,2,opt,name=jobName" json:"jobName,omitempty"`
}

func (m *Register_Job) Reset()         { *m = Register_Job{} }
func (m *Register_Job) String() string { return proto.CompactTextString(m) }
func (*Register_Job) ProtoMessage()    {}

func init() {
	proto.RegisterType((*Register)(nil), "server.Register")
	proto.RegisterType((*Register_Job)(nil), "server.Register.Job")
}
